-- Supabase schema for SpareXpress POS
-- Run this in the Supabase SQL editor or with psql using your direct connection string.

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  size text,
  description text,
  price numeric(10,2) not null default 0,
  stock int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists sales (
  id bigint generated by default as identity primary key,
  ref text not null unique,
  customer text not null default 'Walk-in',
  items jsonb not null,
  subtotal numeric(10,2) not null default 0,
  discount numeric(10,2) not null default 0,
  grand numeric(10,2) not null default 0,
  method text not null default 'CASH',
  sale_time timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  ref text not null unique,
  customer_name text not null,
  phone text,
  email text,
  delivery_address text,
  delivery_method text,
  vin_notes text,
  items jsonb not null,

  total numeric(10,2) not null default 0,
  status text not null default 'NEW',
  processed_at timestamptz,
  created_at timestamptz not null default now()
);
grant select, insert, update, delete on products to anon;
grant select, insert, update, delete on products to authenticated;

grant select, insert, update, delete on sales to anon;
grant select, insert, update, delete on sales to authenticated;

grant select, insert, update, delete on orders to anon;
grant select, insert, update, delete on orders to authenticated;
